name: python-workshop
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy
  - matplotlib
  - netcdf4
  - h5netcdf
  - h5py
  - ipython
  - notebook
  - cartopy
  - pandas
  - s3fs
  # - dask
  - xarray