name: python-workshop
channels:
  - conda-forge
dependencies:
  - python=3.9
  - numpy=1.21.5
  - matplotlib=3.5.1
  - netcdf4=1.5.7
  - h5netcdf=1.1.0 
  - h5py=3.8.0
  - ipython=8.13.1
  - notebook=6.5.4  
  - cartopy=0.20
  - pandas=1.4.2
  - s3fs=2022.5.0
  - dask=2023.4.1
  - xarray=2023.4.2
  - pykdtree=1.3.7.post0
