name: 'Trigger-Binder-build'
on:
  push:

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1
        with:
          target-repo: modern-tools-workshop/ESSIC-workshop-2023/HEAD
          service-name: gh
          debug: true